resources:
- laravel-deployment.yaml
- laravel-service.yaml
- laravel-ingress.yaml
- laravel-hpa.yaml
- laravel-worker-hpa.yaml
- nginx-configmap.yaml
- env-configmap.yaml
- laravel-worker.yaml
- laravel-env-sealed.yaml
#- mysql-pvc.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
